FROM python:3.9.5

RUN apt-get update &&\
 pip install --upgrade pip &&\
 pip install pipenv &&\
 pip install --upgrade setuptools

WORKDIR /workspace

CMD pipenv install && pipenv install --system && python run.py