FROM python:3.9.5

WORKDIR /workspace
COPY ./flask/Pipfile ./
RUN apt-get update &&\
 pip install --upgrade pip &&\
 pip install pipenv &&\
 pip install --upgrade setuptools &&\
 pipenv install &&\
 pipenv install --system


CMD python run.py